const fs = require('fs');

const rawList = `
KID’S HEALTH
PLEXWELL EASSICHEW KIDS CHEWABLE MULTIVITAMIN
PLEXWELL JUNIOR KIDS’ MULTIVITAMIN GUMMIES
PLEXWELL JUNIOR MULTIVITAMIN LIQUID
PLEXWELL BABY MULTIVITAMIN DROPS
PLEXWELL BABY VIT D3 DROPS
PLEXWELL VIT D3+ GUMMIES
MEN’S HEALTH
PLEXWELL MEN MULTIVITAMIN TAB
PLEXWELL MEN 50+ MULTIVITAMIN TAB
PLEXWELL MEN 70+ MULTIVITAMIN POWDER
PLEXWELL MEN 70+ MULTIVITAMIN Spray
PLEXWELL MEN FERTi-PRO TABLET (Fertility Support))
PLEXWELL MEN PROSTi-PRO SOFTGEL (Prostate Health)
PLEXWELL MEN ERECTi-PRO CAPSULE N100 (Sex and Stamina booster)
PLEXWELL MEN ERECTi-PRO CAPSULE N10 (Sex and Stamina booster)
PLEXWELL REGAINOX CAPSULE (Sex and Stamina booster)
PLEXWELL REGAINOX GUMMIES (Sex and Stamina booster)
PLEXWELL RELAUNCH CAPSULE (Sex and Stamina booster)
PLEXWELL MEN HAIR-PRO COMPLEX CAPSULE
PLEXWELL MEN HAIR-PRO COMPLEX EFFERVESCENT
PLEXWELL HAIR-PRO SCALP SERUM
WOMEN’S HEALTH
PLEXWELL WOMEN CAPSULE
PLEXWELL WOMEN 50+ CAPSULE
PLEXWELL WOMEN 70+ POWDER
PLEXWELL MENOPAUSE DAY SUPPORT
PLEXWELL MENOPAUSE NIGHT SUPPORT
PLEXWELL MENSTRU SUPPORT CAPSULE
PLEXWELL UT- SUPPORT CAPSULE
PLEXWELL PCOS SUPPORT COMPLEX CAPSULE
PLEXWELL WOMEN FERTi-PRO CAPSULE
PLEXWELL PREGNENCY SUPPORT Tri-1
PLEXWELL PREGNENCY SUPPORT Tri-2
PLEXWELL PREGNENCY SUPPORT Tri-3
PLXWELL LADYLOVE CAPSULE N10
PLXWELL LADYLOVE CAPSULE N30
MEN & WOMEN WELLNESS POUCHES
PLEXWELL OMEGA FAMILY
PLEXWELL OMEGA SYRUP 200ml
PLEXWELL OMEA SYRUP 150ml
PLEXWELL CODLIVER OIL WITH MULTI VITAMINS 200ml
PLEXWELL SENIOMEGA SYRUP 200ml
PLEXWELL VEGAN OMEGA SOFTGEL
PLEXWELL KRILL OIL SOFTGEL
PLEXWELL OMEGA GUMMIES ADULTS
PLEXWELL OMEGA GUMMIES FOR KIDS
PLEXWELL OMEGA 3-6-9 5in1 FORMULA
PLEXWELL ULTRA OMEGA 15x4 BLISTER
PLEXWELL ULTRA OMEGA N60 BOTTLE
PLEXWELL OMEGA + Probiotics + Curcumin SOFTGEL
PLEXWELL OMEGA + VIT E SOFTGEL
PLEXWELL OMEGA + VIT D3 + VIT E + CoQ10 + CURCUMIN SOFTGEL
PLEXWELL OMEGA-α SOFTGEL
PLEXWELL FERROLYTE IRON SUPPLEMENT FAMILY
FERROLYTE SR CAPSULE
FERROLYTE LIQUID 200ML
FERROLYTE LIQUID PLUS 200ML
FERROLYTE GUMMIES FOR KIDS
FERROLYTE EASSiCHEW TABLETS FOR KIDS
ANTI-AGING AGESLOW COMPLEX
AGE-SLOW CAPS
AGE-SLOW CAPS 70+ AGE
AGE-SLOW COMPLEX BITTER DROPS
AGE-SLOW COMPLEX GUMMIES
AGE-SLOW COMPEX POWDER
AGE-SLOW COMPLEX SHOTS
PLEXWELL VITAMIN C SUPPLEMENT’S
PLEXWELL VIT C+ TAB
PLEXWELL VIT C+ EFFERVESCENT
PLEXWELL VIT C+ GUMMIES
PLEXWELL VIT C+ POWDER SACHET
PLEXWELL VIT D3 SUPPLEMENT’S
PLEXWELL VIT D3 BABY DROPS
PLEXWELL VIT D3 GUMMIES
PLEXWELL VIT D3 TABLETS FOR KIDS 4-10 Y
PLEXWELL VIT D3+ MULTIVITAMIN SYRUP 3-15 Y
PLEXWELL Vit D3 TABLET FOR TEENS
PLEXWELL VIT D3 5000 IU ADULT
PLEXWELL VIT D3 10000 IU ADULT
PLEXWELL VIT D3 20000 IU ADULT
PLEXWELL VIT D3+ EFFERVESCENT
PLEXWELL VIT D3+ COD LIVER OIL + OMEGA 3 SOFTGEL
PLEXWELL CALCIUM + OTHER SUPPLEMENT’S
PLEXWELL KIDCAL SYRUP 200ML
PLEXWELL OSTEOMAX LIQUID 200ML
PLEXWELL OSTEOMAX EFFERVESCENT
PLEXWELL OSTEOMAX+ SOFTGEL
PLEXWELL OSTEOMAX TABLET
PLEXWELL OSTEOMAX GUMMIES FOR KIDS
PLEXWELL BEAUTY SUPPLEMENT’S
PLEXWELL HAIR, SKIN AND NAILS TABLETS
PLEXWELL BEAUTY POUCH FOR HER
PLEXWELL BEAUTY COLLAGEN MATRIX POWDER
PLEXWELL BEAUTY COLLAGEN MATRIX CAPSULE
PLEXWELL BEAUTY SKIN-CLEAR MATRIX CAPSULE
PLEXWELL BEAUTY GLOW-MATRIX CAPSULE
PLEXWELL NIACINAMIDE 250MG TABLET
PLEXWELL NIACINAMIDE 500MG TABLET
PLEXWELL ANTI ACNE COMPLEX TABLET
PLEXWELL SLEEP SUPPLEMENT’S
PLEXWELL SOMNA-MATRIX CAPSULE
PLEXWELL SOMNA-MATRIX GUMMIES
PLEXWELL SOMNA-MATRIX SPRAY
PLEXWELL EYE/VISION SUPPLEMENT’S
PLEXWELL OPHTHACARE JUNIOR SYRUP
PLEXWELL OPHTHACARE CAPSULE
PLEXWELL OPHTHACARE AGE 60+ CAPSULE
PLEXWELL OPHTHACARE GUMMIES
PLEXWELL OPHTHACARE EFFERVESCENT
PLEXWELL COUGH REMEDIES (HERBAL)
PLEXWELL COUGH-CARE JUNIOR
PLEXWELL COUGH-CARE
PLEXWELL COUGH-CARE DAY SACHET
PLEXWELL COUGH-CARE NIGHT SACHET
PLEXWELL PRE- PRO- AND POST-BIOTICS
PLEXWELL KIDS DIGESMART GUMMIES
PLEXWELL DIACARE ORAL SACHET
PLEXWELL TRI-BIOTIC GUMMIES
PLEXWELL FLORA BALANCE CAPSULE
PLEXWELL UTI-BIOTIC CAPSULE
PLEXWELL UTI-BIOTIC SYRUP 150ml
`;

const lines = rawList.trim().split('\n').map(l => l.trim()).filter(Boolean);
const products = [];
let currentCategory = "General";

for (const line of lines) {
    if (!line.includes("PLEXWELL") && !line.includes("FERROLYTE") && !line.includes("AGE-SLOW") && !line.includes("PLXWELL") && line === line.toUpperCase()) {
        currentCategory = line;
    } else {
        const id = line.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
        products.push({
            id: id,
            category: currentCategory,
            name: line,
            image: "/pharma/assets/images/663c6d1a1cb8e.png", // Generic placeholder
            description: "Advanced formulation for optimal health and wellness.",
            ingredients: [
                { name: "Active Ingredient A", dosage: "50mg", dv: "50%" },
                { name: "Vitamin B Complex", dosage: "10mg", dv: "100%" }
            ],
            features: [
                "High absorption formula",
                "Clinically tested",
                "Premium quality ingredients"
            ]
        });
    }
}

if (!fs.existsSync('data')) {
    fs.mkdirSync('data');
}
fs.writeFileSync('data/products.json', JSON.stringify(products, null, 2));
console.log('Saved data/products.json with ' + products.length + ' products.');
